spring:
  data:
    mongodb:
      username: pooya
      password: 05121
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin

  application:
    name: customer-service

server:
  port: 8090



